using System;
using System.Collections.Generic;

namespace Agility.DomainModel
{
    public class Project
    {
        private long _projectId;
        private string _name;
        private string _descreption;
        private DateTime _startDate;
        private DateTime _endDate;

        /// <summary>
        /// Represents unique, autogenerated id.
        /// </summary>
        public virtual long ProjectId
        {
            get { return _projectId; }
            set { _projectId = value; }
        }
        /// <summary>
        /// Represents the name of the project. Name must be unique.
        /// </summary>
        public virtual string Name 
        { 
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// Represents project description.
        /// </summary>
        public virtual string Description 
        { 
            get { return _descreption; }
            set { _descreption = value; }
        }

        /// <summary>
        /// Reperesents the start date of project.
        /// </summary>
        public virtual DateTime StartDate 
        { 
            get { return _startDate; }
            set { _startDate = value; }
        }

        /// <summary>
        /// Represents date by which the project must be finished.
        /// </summary>
        public virtual DateTime EndDate 
        { 
            get { return _endDate; }
            set { _endDate = value; }
        }

        /// <summary>
        /// Reperesents a list of users working on the project.
        /// </summary>
        public virtual IList<User> Members { get; set; }

        /// <summary>
        /// Reperesents a list of Sprints created in project.
        /// </summary>
        public virtual IList<Sprint> Sprints { get; set; }

        /// <summary>
        /// Represents product backlog of this project.
        /// </summary>
        public virtual ProductBacklog Backlog { get; set; }

        public Project()
        {

        }

        public Project(string name, string description, DateTime startDate, DateTime endDate, List<User> members)
        {
            Name = name;
            Description = description;
            StartDate = startDate;
            EndDate = endDate;
            Members = members;
        }

    }
}
