using System;
using System.Collections.Generic;
using System.Text;

namespace Agility.DomainModel
{
    public class Requirement
    {
        private long _requirementId;
        private RequirementType.TypeEnum _type;
        private RequirementPriority.PriorityEnum _priority;
        private bool _done;
        private string _title;
        private string _description;
        private ProductBacklog _backlog;

        /// <summary>
        /// Represents unique, autogenerated id.
        /// </summary>
        public virtual long RequirementId
        {
            get { return _requirementId; }
            set { _requirementId = value; }
        }

        /// <summary>
        /// Represents the type of a requrement. Types are: FEATURE, BUG_FIX, NON_FUNCTIONAL
        /// </summary>
        public virtual RequirementType.TypeEnum Type
        {
            get { return _type; }
            set { _type = value; }
        }

        /// <summary>
        /// Represents requirement title.
        /// </summary>
        public virtual string Title
        {
            get { return _title; }
            set { _title = value; }
        }

        /// <summary>
        /// Represents requirement description
        /// </summary>
        public virtual string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>
        /// Represents requirement priority. Priority can be: HIGH, MEDIUM and LOW
        /// </summary>
        public virtual RequirementPriority.PriorityEnum Priority
        {
            get { return _priority; }
            set { _priority = value; }
        }

        /// <summary>
        /// Represents if requirement is implemented or not.
        /// </summary>
        public virtual bool RequirementDone
        {
            get { return _done; }
            set { _done = value; }
        }

        /// <summary>
        /// Represents task breakdown of a requirement. Rwquirement must have at least one task.
        /// </summary>
        public virtual IList<Task> RequirementTasks { get; set; }


        /// <summary>
        /// Represents product backlog that this requirement is part of.
        /// </summary>
        public virtual ProductBacklog Backlog
        {
            get { return _backlog; }
            set { _backlog = value; }
        }

        public Requirement() { }

        public Requirement(RequirementType.TypeEnum type, string title, string description, RequirementPriority.PriorityEnum priority, IList<Task> requirementTasks)
        {
            Title = title;
            Type = type;
            Description = description;
            Priority = priority;
            RequirementTasks = requirementTasks;
            RequirementDone = false;
        }

    }
}
