using System;
using System.Collections.Generic;

namespace Agility.DomainModel
{
    public class Sprint
    {
        private long _sprintId;
        private DateTime _start;
        private DateTime _end;
        private string _name;
        private Project _project;

        /// <summary>
        /// Represents unique, autogenerated id.
        /// </summary>
        public virtual long SprintId
        {
            get { return _sprintId; }
            set { _sprintId = value; }
        }
        /// <summary>
        /// Represents start date of sprint.
        /// </summary>
        public virtual DateTime StartDate
        {
            get { return _start; }
            set { _start = value; }
        }

        /// <summary>
        /// Represents end date of sprint.
        /// </summary>
        public virtual DateTime EndDate
        {
            get { return _end; }
            set { _end = value; }
        }

        /// <summary>
        /// Represents sprint name.
        /// </summary>
        public virtual string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// Represents a list of tasks selected for sprint.
        /// </summary>
        public virtual IList<Task> SprintTasks { get; set; }

        /// <summary>
        /// Represents project that this Sprint is part of.
        /// </summary>
        public virtual Project Project
        {
            get { return _project; }
            set { _project = value; }
        }

        public Sprint() { }

        public Sprint(DateTime startDate, DateTime endDate, string name, List<Task> sprintTasks)
        {
            StartDate = startDate;
            EndDate = endDate;
            Name = name;
            SprintTasks = sprintTasks;
        }

    }
}
