using System;
using System.Collections.Generic;
using System.Text;

namespace Agility.DomainModel
{
    public class Task
    {
        private long _taskId;
        private string _description;
        private User _member;
        private TaskStatus.StatusEnum _status;
        private Requirement _requirement;
        private Sprint _sprint;

        /// <summary>
        /// Represents unique, autogenerated id.
        /// </summary>
        public virtual long TaskId
        {
            get { return _taskId; }
            set { _taskId = value; }
        }
        /// <summary>
        /// Represents task description. 
        /// </summary>
        public virtual string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>
        /// Represents project member working on task.
        /// </summary>
        public virtual User MemberWorking
        {
            get { return _member; }
            set { _member = value; }
        }

        /// <summary>
        /// Represents task status. Status can be: IN_PROGRESS, STUCK, DONE.
        /// </summary>
        public virtual TaskStatus.StatusEnum Status
        {
            get { return _status; }
            set { _status = value; }
        }

        /// <summary>
        /// Represents the requirement that task is part of.
        /// </summary>
        public virtual Requirement Requirement
        {
            get { return _requirement; }
            set { _requirement = value; }
        }

        /// <summary>
        /// Represents Sprint that the task is selected for. Can be null.
        /// </summary>
        public virtual Sprint Sprint
        {
            get { return _sprint; }
            set { _sprint = value; }
        }

        public Task() { }

        public Task(string description)
        {
            Description = description;
            Status = TaskStatus.StatusEnum.TO_DO;
        }

    }
}
